CREATE TABLE IF NOT EXISTS Users (
    userID TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    passwordHash TEXT UNIQUE NOT NULL,
    winCount INTEGER DEFAULT 0 NOT NULL CHECK(winCount >= 0)
);

CREATE TABLE IF NOT EXISTS GameTable (
    tableID TEXT NOT NULL,
    userID TEXT NOT NULL,
    FOREIGN KEY (userID) REFERENCES Users(userID) 
);

CREATE TABLE IF NOT EXISTS GameState (
    state TEXT
);